{ pkgs, inputs, ... }: {
  home.packages = with pkgs; [
    zip
    xz
    unzip
    ripgrep
    lazygit
    jq
    fzf
    fd
    which
    nix-output-monitor
    btop
    strace
    ltrace
    lsof
    sysstat
    gcc
    luarocks
    lua
    cargo
    httpie
    nixfmt-classic
    wl-clipboard
    haskell.compiler.ghc910
    cabal-install
    brightnessctl
    (haskell-language-server.override { supportedGhcVersions = [ "910" ]; })
    neovide
    playerctl
    wlogout
    isabelle
    emacs
    nh
    libnotify
    glib
    uv
    nodejs
    vscode
    inputs.zen-browser.packages.${pkgs.system}.default
  ];
}
